apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: buildpod
spec:
  containers:
    - name: docker
      image: docker:20.10
      command:
        - cat
      tty: true
      privileged: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
    - name: minio
      image: minio/mc
      env: 
      - name: TZ
        value: Asia/Tokyo
      command:
        - cat
      tty: true
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
