apiVersion: v1
kind: Pod
metadata:
  labels:
    some-label: buildpod
spec:
  containers:
    - name: docker
      image: docker:20.10
      command:
        - cat
      tty: true
      privileged: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: oracle-images
          mountPath: /mnt/oracle-images
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
    - name: oracle-images
      persistentVolumeClaim:
        claimName: pvc-oracle-images
