pipeline {
    environment {
        REGISTRY_HOST = 'harbor.dev.asg.x.recruit.co.jp'
        REGISTRY_CREDENTIAL = credentials('jenkins-harbor')
    }
    agent {
        kubernetes {
            defaultContainer 'jnlp'
            yamlFile 'OracleDatabase/SingleInstance/dockerfiles/jenkins-pod.yml'
        }
    }
    stages {
        stage('build 19c image') {
            steps {
                container('docker') {
                    dir(path: 'OracleDatabase/SingleInstance/dockerfiles/19.3.0') {
                        sh 'cp -p /mnt/oracle-images/LINUX.X64_193000_db_home.zip .'
                        sh 'ls -la'
                        // bashが無くてエラーになる。。ので、内部で呼んでいるビルドコマンドを直接呼ぶ
                        //sh 'sh buildContainerImage.sh -e -v 19.3.0 -t ${REGISTRY_HOST}/oracle/database:19.3.0-ee-20220825'
                        sh "docker build --force-rm=true --no-cache=true --build-arg DB_EDITION=ee -t ${REGISTRY_HOST}/oracle/database:19.3.0-ee-20220825 -f Dockerfile ."
                        sh "docker login -u ${REGISTRY_CREDENTIAL_USR} -p ${REGISTRY_CREDENTIAL_PSW} ${REGISTRY_HOST}"
                        sh "docker push ${REGISTRY_HOST}/oracle/database:19.3.0-ee-20220825"
                    }
                }
            }
        }
    }
}
